# site settings
title: NodeSydney
email: contact@nodesydney.com
description: Your local Node.js community
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address:
city: Sydney
state: NSW
zip_code: 2000
country: Australia
phone:

# social settings
500px_url:
facebook_url:
github_url: https://github.com/nodesydney
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url: https://nodesydney.slack.com
twitter_url: https://twitter.com/nodesydney

# build settings
markdown: kramdown

sass:
  style: compressed
